# command line: main.py --config ./config/uav/angle_FR_Head_1.yaml --work-dir ./work_dir/angle_FR_Head_1

amp_opt_level: 1
balanced_sampling: false
base_lr: 0.1
batch_size: 128
cl_mode: ST-Multi-Level
config: ./config/uav/angle_FR_Head_1.yaml
data_path: ../data/angle/train_angle_joint.npy
debug: false
device: 0
eval_interval: 5
feeder: feeders.feeder_uav.Feeder
focal_loss: false
graph: graph.uav.Graph
half: true
ignore_weights: []
in_channels: 9
k: 1
label_path: ../data/train_label.npy
lambda_1: 0.0001
lambda_2: 0.1
log_dir: .
log_interval: 100
lr_decay_rate: 0.1
model_saved_name: ''
n_desired: 40000
n_heads: 3
nesterov: true
noise_ratio: 0.5
num_class: 155
num_epoch: 110
num_person: 2
num_point: 17
num_worker: 4
optimizer: SGD
phase: train
print_log: true
random_rot: false
repeat: 1
save_epoch: 90
save_interval: 100
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 90
- 100
test_batch_size: 128
test_data: ../data/angle/test_angle_joint_A.npy
test_label: ../data/test_label_A.npy
use_angle: true
use_vel: false
w_cl_weights: 0.1
warm_up_epoch: 5
weight_decay: 0.0005
weights: null
window_size: 64
work_dir: ./work_dir/angle_FR_Head_1
z_prior_gain: 3
